### ISSUE TITLE
SMS showing as pending but sent

### ISSUE THREAD

**Issue by bigjv12** [sidneys/pb-for-desktop#43]
When using PB for desktop to send a text message to a contact the message sends correctly from the phone, and appears in the message conversation in the app but also stays grayed out saying pending at the bottom of the message list.

When i log into the PB website directly there are no pending grayed out messages.

I am using V5.4.1 on Ubuntu

**Comment by bigjv12** [comment]
If i log out and log in again the pending ones go but as soon as i send a message they start again

**Comment by andresilva** [comment]
I'm also seeing the same behavior with v5.4.4 on macOS.

**Comment by sidneys** [comment]
@bigjv12 @andrebeat 

This has been addressed as of v5.5.0, [please update](../releases) and submit feedback. Thanks.

**Comment by bigjv12** [comment]
Thank you will you be posting a deb?

**Comment by andresilva** [comment]
I've built the latest version for macOS and the issue is still there for me. I've tried logging out and in of the account which clears all the pending messages. After I've sent a new sms it was duplicated, one delivered and one pending.

**Comment by bigjv12** [comment]
Hello, i have installed the 5.5.0 linux 64-bit deb.  I logged out and logged back in and the problem still happens I'm afraid.

**Comment by bigjv12** [comment]
I have updated to 5.5.1 and the problem still persists

**Comment by sidneys** [comment]
@andrebeat @bigjv12 

Due to your quick feedback another approach at fixing this just landed in [v5.6.0](../releases), awaiting further comments.

**Comment by bigjv12** [comment]
Hello

Sorry for the delay, I have just installed 5.6.0 logged out and logged in, sent an sms and the pending issue seems to have been resolved.

Thank you for fixing it.

**Comment by sidneys** [comment]
@bigjv12 Great stuff. Happy easter :-)
