### ISSUE TITLE
High resource usage in mac os

### ISSUE THREAD

**Issue by bjptwist** [sidneys/pb-for-desktop#67]
## 🤷🏽‍♂️ Current Behaviour

Hi. I'm using version 6.0.7 and I'm having the exact same issue with high cpu consumption. Basically, if I quit the app and start it again the average cpu usage is around 2,0, being one of the top battery consuming apps. As soon as I open the main window (clicking in "Show PB for Desktop") and close it, the cpu usage drops right away.

## 🎯 Expected Behaviour

The app should not use almost any resource when it is not being used.

## 🏡 Environmental Context

**App Version**
v6.0.7
**Operating System**
MacOs Sierra (10.12)

**Comment by levinit** [comment]
linux,too

**Comment by levinit** [comment]
![2017-10-04 12-23-07](https://user-images.githubusercontent.com/24387319/31159925-211d3e7e-a8ff-11e7-8216-dfbc0f74713e.png)
it use 3.9G memory   ， lead to system crash

**Comment by sidneys** [comment]
Hi @bjptwist, @levinit 

This issue has been addressed in v6.1.6, looking forward to your feedback 😎.

Cheers, S

**Comment by bjptwist** [comment]
The issue persists. If you follow the exact steps I mentioned before:
1 - lanuch the app
2 - check the activity monitor in mac os and see the cpu usage is constantly around 2,0.
3 - In the main window click in "Show PB for Desktop"
4 -  check the activity monitor and see the cpu usage dropped to around 0,0

**Comment by levinit** [comment]
@bjptwist 2% is already very low for runing front, when it  runs in  background, cpu usage is 0%.

**Comment by bjptwist** [comment]
I may have explained my self wrong. 2% is for the app in background when I just started the app without opening the main window. As soon I open it and close it again, the consumption drops to 0% right away. This leads me to believe there is a bug until the main window is opened which causes the high consumption.

**Comment by sidneys** [comment]
@levinit @bjptwist 
Thanks for the recent observations. Any updates with regards to performance with the latest version?

Cheers,
S

**Comment by bjptwist** [comment]
Apparently its fixed in the latest version. However, now when I let the computer sleep for several minutes and wake it up, the app doesn't seem to recover the connection with PB. I have to restart the application in order to get connection back.

**Comment by levinit** [comment]
@sidneys  That problem never happened again in new ver, thx.

**Comment by sidneys** [comment]
@bjptwist @levinit 

Thanks guys. Closing this for now.

@bjptwist 

If the reconnection problem reoccurs, please create a new issue to follow up on it.

Cheers,
S

**Comment by jimjam-slam** [comment]
I've installed 6.7.7 onto my Mac (macOS 10.13.2) and am having the same problem as @bjptwist: when I start the program or resume the Mac after sleep, I'm finding that one of the PB for Desktop Helpers consistently uses 12–14% CPU even when the app is in the background.

<img width="815" alt="screenshot 2018-01-15 22 32 21" src="https://user-images.githubusercontent.com/6520659/34940521-ef064c50-fa43-11e7-8c2f-b71ec6f4e3e7.png">

But if I 'Show PB for Desktop' and then close it, consumption immediately drops:

<img width="815" alt="screenshot 2018-01-15 22 34 21" src="https://user-images.githubusercontent.com/6520659/34940601-36e5fdd6-fa44-11e7-8108-9f3305e7ae23.png">

**Comment by mobeigi** [comment]
@sidneys Are there any known battery issues with latest builds? I recently installed this on my macos as replacement for Noti and suddenly my mac loses battery super fast. Loses huge amounts of % in sleep mode and activity monitor reports insanely high energy impact compared to every other app.

Going to uninstall for now which is a shame as it was pretty useful.
