### ISSUE TITLE
People added by mobile phone are MISSING in desktop app.

### ISSUE THREAD

**Issue by dayfuaim** [sidneys/pb-for-desktop#82]
## 🏽‍♂️ Current Behaviour
I have added my mother from her mobile phone (and using mobile number, not e-mail address). I see her using extensions (Chrome/Firefox) and in mobile apps, but _**not** in desktop app_ and _via website_.
Nevertheless, I receive notifications from her into desktop app.

## 🎯 Expected Behaviour
I must see added people everywhere: extensions, mobile apps, website.

## 👟 Steps to Reproduce (S2R)

 1. Add people via mobile app (using mobile phone number, **not e-mail address**).
 2. Open desktop app.
 3. These people are missing in "People".

## 🏡 Environmental Context
**App Version**
v6.7+
**Installation Type** 
Setup
**Operating System**
OSX Yosemite 10.10.5

**Comment by sidneys** [comment]
@dayfuaim 

We could not reproduce this error. Does it still occur?

Cheers,
S

**Comment by dayfuaim** [comment]
Unfortunately, yes.
I still do not see phone-added contact in "People".
Extension:
![2018-08-27 13 45 27](https://user-images.githubusercontent.com/1274699/44655904-8650d880-a9ff-11e8-9e72-f4cc4623d135.png)

App:
![2018-08-27 13 46 27](https://user-images.githubusercontent.com/1274699/44655938-a54f6a80-a9ff-11e8-824b-50fb4e6a3a40.png)

Sorry for Russian.

**Comment by sidneys** [comment]
@dayfuaim 

Has this issue been resolved with the recent releases? Reproducing it has been impossible.

Cheers, S

**Comment by dayfuaim** [comment]
Yes, the issue is still here.
PB for Desktop v8.18.2
Chrome extension v344

**Comment by sidneys** [comment]
@dayfuaim Cannot be reproduced on v10, please re-test.
